version: '3.8'
services:
  dev:
    image: mcr.microsoft.com/devcontainers/dotnet:9.0
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - postgres
    ports:
      - "5000:5000"
      - "5001:5001"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"